name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Set this to your default branch
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Changed to a more stable version

      - name: Install dependencies
        run: npm ci

      - name: Install markdown-to-html converter
        run: npm install -g markdown-to-html-cli

      - name: Convert README to HTML
        run: markdown-to-html-cli README.md > documentation.html

      - name: Build
        run: |
          npm run build
          mv documentation.html dist/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
